# Generated by Django 4.0.4 on 2022-05-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='freelance',
            field=models.BooleanField(default=True, null=True, verbose_name='Freelance'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='open_to_work',
            field=models.BooleanField(default=True, null=True, verbose_name='Open to Work'),
        ),
    ]
