# Generated by Django 4.0.4 on 2022-05-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.CharField(max_length=70, null=True, verbose_name='Enterprise/Company')),
                ('position', models.CharField(max_length=70, null=True, verbose_name='Position')),
                ('started_at', models.DateField(null=True, verbose_name='Started at')),
                ('finished_at', models.DateField(blank=True, null=True, verbose_name='Finished at')),
                ('is_on', models.BooleanField(default=True, verbose_name='Still Working?')),
            ],
        ),
    ]
