# Generated by Django 4.0.4 on 2022-05-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=70, null=True, verbose_name='School/Campus')),
                ('education_level', models.CharField(max_length=70, null=True, verbose_name='Education Level')),
                ('started_at', models.DateField(null=True, verbose_name='Started at')),
                ('finished_at', models.DateField(null=True, verbose_name='Finished at')),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Studying', 'Studying'), ('Stopped', 'Stopped')], max_length=30, null=True)),
            ],
        ),
    ]
