# Generated by Django 4.0.4 on 2022-05-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HardSkills',
            new_name='HardSkill',
        ),
        migrations.RenameModel(
            old_name='SoftSkills',
            new_name='SoftSkill',
        ),
    ]
